### PR TITLE
Feature: Pydantic Models

### PR DESCRIPTION
**Pull request by willsawyerrrr**
- **Improve API constructor validations**
- **Convert `typing.TypedDict`s to `pydantic.BaseModel`s**

### CODE REVIEW

**Review by andre-at-situ — COMMENTED** [review]
Any tests required or will this change just auto work?

**Comment by willsawyerrrr** [comment]
> Any tests required or will this change just auto work?

The changes are only to typing, not to logic.

That being said, I've just realised I didn't change the usage of the types, so maybe I should add tests...

**Comment by andre-at-situ** [comment]
This will be breaking on anything that uses it I think so version number will need to be bumped.

**Review by andre-at-situ — APPROVED** [review]
Approved pending version bump.

**Pull request merged**
